### ISSUE TITLE
您是怎么修复nav的二级激活状态的呀?

### ISSUE THREAD

**Issue by carveybunt** [Dragon1573/Study-Notes#1]
`vuepress`  `vdoing`  他们的`navbar`激活二级时，一级`navnar`都没有激活状态。您的这个项目却修复了这个问题，能请教下是怎么修复的吗？

**Comment by Dragon1573** [comment]
> `vuepress-theme-vdoing` 他们的 `navbar` 激活二级时，一级 `navbar` 都没有激活状态。

还不是很明白您指的是什么？能详细描述一下吗？最好能够提供截图

**Comment by carveybunt** [comment]
> 
您的项目的导航存在二级的时候，一级导航也是下划线![1](https://user-images.githubusercontent.com/37894474/147086674-dc77bf14-9469-40fa-9eab-8abda7cac922.png)

vdoing 以及 vuepress 的如下
![2](https://user-images.githubusercontent.com/37894474/147086682-ed6dc4fd-900a-445a-bd23-13ec9d412418.png)

**Comment by Dragon1573** [comment]
1. 你说的这种情况我也不太清楚，我并没有人为修改 Vdoing 相关的样式配置
2. 相较于 **Evan's Blog** ，我自己的站点在 `class` 处会多一个 `router-link-active` ，至于为什么会存在这个东西就不知道了

关于这个问题，我觉得可以请教一下 @xugaoyi.

**Comment by carveybunt** [comment]
@Dragon1573 您是在哪里加的呢？能分享下吗。

**Comment by Dragon1573** [comment]
被激活的导航项应该是会自动添加 `router-link-active` 这个 `class` 的，但 **Vdoing** 开 `F12` 后并没有在页面源代码里发现它。

在 **Evan's Blog** 右上角可以直接前往他的 GitHub 仓库，像这样开个 Issues 问一下（最好先在 Issues 里搜索一下，看看有没有人提到这个），顺便使用 `Dragon1573/Study-Notes#1` 这个写法与此 Issues 建立关联，这样他可以直接跳过来查看我的源代码，这样或许能够方便他发现区别。

**Comment by carveybunt** [comment]
@Dragon1573 多谢我试试

**Comment by Dragon1573** [comment]
xugaoyi/vuepress-theme-vdoing#358 也有不少使用了 **Vdoing** 主题的其他站点，也可以去参观一下，他们好像也不一定会显示这个效果。我自己刚刚才申请加入收录的（手动滑稽.png）

**Comment by carveybunt** [comment]
@Dragon1573  大佬，您的这个`markdown-it-mathjax3`是怎么配置的呀？
我也是按照
```
yarn add markdown-it-mathjax3
```
修改`config.js`：
```js
  extendMarkdown: md => {
    ……
    md.use(require('markdown-it-mathjax3'));
    ……
  }
```
但是并未成功渲染相关的数学公式。

**Comment by Dragon1573** [comment]
@carveybunt , @tani 已经就此问题进行了解释：

- 引起这个报错的原因： https://github.com/tani/markdown-it-mathjax3/issues/54#issuecomment-1000143636
- 现行的解决方案： https://github.com/tani/markdown-it-mathjax3/issues/54#issuecomment-1000145613

我相信您可能和其他用户一样，都是由于我在B站的发言找到这里的，因此我会向 @tani 申请将以上 Issues 置顶，提醒其他用户进行临时降级，等待新版本的发布。

**Comment by carveybunt** [comment]
@Dragon1573  多谢，要是`vdoing` `markdown-it-mathjax3`都能更新支持`vuepress 2`就好了。

**Comment by Dragon1573** [comment]
根据 [VuePress v2.x](https://v2.vuepress.vuejs.org/) 官网所写的版本号，当前最新版本是 `v2.0.0-beta.29` ，仍处在 Beta 公测状态。我想，在 `v2.x` 变更为 Stable 正式版并接棒 `v1.x` 、`v1.x` 进入 EoL (End of Life) 状态前，这些依赖项可能都不会选择添加 `v2.x` 支持。

**Comment by carveybunt** [comment]
嗯嗯，多谢了。先用着，要学备考，没时间研究这些东西。

**Comment by Dragon1573** [comment]
@tani 已经正式发布 `markdown-it-mathjax3@3.1.1` ，经测试此版本能够正常被导入。请大家尽快更新至 `v3.1.1` 版本 ❤️
