### ISSUE TITLE
为什么用您的项目部署到github pages 样式失效呀？

### ISSUE THREAD

**Issue by carveybunt** [Dragon1573/Study-Notes#2]
用的`deploy.sh`脚本部署，部署成功后，页面样式无效。
![1](https://user-images.githubusercontent.com/37894474/147261209-781b2864-6f28-46a5-bd2e-455b80f63385.jpg)
![2](https://user-images.githubusercontent.com/37894474/147261221-6254a392-336e-4933-a3d6-8c9aaad5b599.jpg)

**Comment by Dragon1573** [comment]
@carveybunt 关于您上面提及的『CSS 样式失效』，可能与以下内容有关系：

1. 项目根链接的问题

   > 您没有更改 `config.js` 中的 [`module.exports.base`](https://github.com/Dragon1573/Study-Notes/blob/main/docs/.vuepress/config.js#L8) 值。 `base` 值指定了整个项目的『根链接』，所有文件部署上线后都是相对这个『根链接』构造相应的资源引用或超链接的。
   >
   > 我为本项目配置了 CNAME 域名解析，让 GitHub Pages 能够部署到我自己持有的二级域名上（ https://blog.dragon1573.wang/ ），因此我的项目是直接部署于域名顶级目录中的，此时 `base` 需要被直接设置为 `"/"` 。但您移除了以上 CNAME 信息，GitHub Pages 会默认发布于 `https://<owner>.github.io/<repository>` 形式的站点目录下。
   >
   > 我看到您在 `deploy.sh` 中使用的仓库链接为 `git@github.com:carveybunt/blog.git` ，因此最终部署的站点链接是您截图中的 `https://carveybunt.github.io/blog/` 。此时，您的项目根目录不再位于域名服务器的根目录，而是位于 `/blog/` 子目录下，因此您需要将 `base` 设置为 `/blog/` 。
   >
   > 有关 `config.js` 中 `module.exports.base` 设置项的更多信息，请查阅 [VuePress v1.x 官方文档](https://v1.vuepress.vuejs.org/zh/config/#base) 。

2. 项目部署的形式（人为部署 `gh-pages` 分支）

   > 首先，我在本项目中从未使用过此 `deploy.sh` 文件（可能是由 @xugaoyi 配套提供的？）。我为本仓库配置了 GitHub Workflows ，让项目在 GitHub 提供的虚拟环境中完成编译构建，并自动部署到 GitHub Pages 中。
   >
   > 我个人不太推荐自行维护 `gh-pages` 分支，请专注于自己博客内容的高质量产出、将这些琐事全部交给 GitHub Workflows 去完成吧！关于我是如何配置 GitHub Workflows 的，请查阅 [`.github/workflows/vuepress.yml`](https://github.com/Dragon1573/Study-Notes/blob/main/.github/workflows/vuepress.yml) 。

**Comment by carveybunt** [comment]
@Dragon1573 非常感谢，`base` 的设置确实是我疏忽大意了。不过手动布置确实麻烦，我也是刚用`vuepress` `github pages`，我正在尝试`workflows`部署。
