### ISSUE TITLE
用您的包无法直接升级依赖呀？

### ISSUE THREAD

**Issue by carveybunt** [Dragon1573/Study-Notes#3]
![1](https://user-images.githubusercontent.com/37894474/147380833-29e9bbc2-5a20-4fa2-995e-57d14b88408a.png)

我移除包
`yarn remove markdown-it-mathjax3 `
之后重新安装直接报错了
![2](https://user-images.githubusercontent.com/37894474/147380906-5253ffe5-f7be-4562-b012-464f66ce0fe6.png)

**Comment by Dragon1573** [comment]
1. 首先，Yarn 并没有 `upgrade` 这个子命令，我也没有试过以这种方式进行升级。Yarn 提供了一种更直观、更友好的依赖项升级方式，借助 `yarn upgrade-interactive` 命令可以实现。需要注意的是，此处的 `upgrade-interactive` 是 **一个整体** 。
2. 按照您第2个报错来看，产生的错误信息是 `RequestError: read ECONNRESET` ，Yarn 无法检索到合适的软件版本范围，这种情况极大可能是网络异常导致的（NPM 源和 Yarn-pkg 源全部位于大陆境外）。根据 @tani 之前给我的建议，我同样也建议您更换使用位于中国大陆境内的镜像源，优先选择与国际官方镜像同步频率和稳定性最高的 [淘宝 CNPM 源](https://npmmirror.com/) 。Yarn-pkg 官方源本身也只是 NPM 官方依赖项仓库的另一个入口，与 NPM 官方源入口指向的仓库位置完全相同，所以 Yarn 也是支持 NPM 镜像源地址的。

<details>
<summary>新建项目并安装 <code>markdown-it-mathjax3</code> </summary>

```text
sample λ yarn init -y
yarn init v1.22.15
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
Done in 0.11s.

sample λ yarn set version berry
➤ YN0000: Retrieving https://repo.yarnpkg.com/3.1.1/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-3.1.1.cjs
➤ YN0000: Done in 5s 295ms

sample λ yarn add markdown-it-mathjax3 -D
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 2s 713ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ web-resource-inliner@npm:5.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ webidl-conversions@npm:3.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ whatwg-url@npm:5.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ wicked-good-xpath@npm:1.3.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ xmldom-sre@npm:0.1.31 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 0s 942ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 3s 862ms

sample λ yarn info
├─ markdown-it-mathjax3@npm:3.1.1
│  ├─ Version: 3.1.1
│  │
│  └─ Dependencies
│     ├─ juice@npm:^8.0.0 → npm:8.0.0
│     └─ mathjax-full@npm:^3.2.0 → npm:3.2.0
│
└─ sample@workspace:.
   ├─ Version: 1.0.0
   │
   └─ Dependencies
      └─ markdown-it-mathjax3@npm:^3.1.1 → npm:3.1.1
```

</details>

**Comment by carveybunt** [comment]
@Dragon1573 可能是您用的 `yarn`版本或者其他地方有设置。 我在`vdoing`项目里是可以使用`yarn upgrade`命令的。

**Comment by Dragon1573** [comment]
需要说明的是，根据 Yarn v2.x 官方文档的安装说明，你应该在全局范围使用 Corepack 或 NPM 安装 Yarn v1.22.11 ，并仅在项目的作用域内将 Yarn 升级到 v2.x （当前为 v3.1.1 ）。我的项目中拥有 `.yarn/releases/yarn-3.1.1.cjs` ，在 `package.json` 中也指明了 `"packageManager": "yarn@3.1.1"` 。

Yarn v2.x 相比于 v1.x 做出了大量的改进，移除了 `upgrade` 命令，同时 `yarn global` 命令也变成了 `yarn dlx` 命令。两者之间的更多区别，也请查阅官方文档。

**Comment by carveybunt** [comment]
@Dragon1573 多谢，我猜应该也是版本的问题，等不忙了在去研究 `yarn 3`.
