### ISSUE TITLE
为什么自动自定义容器用不了了呀？

### ISSUE THREAD

**Issue by carveybunt** [Dragon1573/Study-Notes#4]
```
::: tip
这是一条提示
:::

::: warning
这是一条注意
:::

::: danger
这是一条警告
:::

::: note
这是笔记容器，在 <Badge text="v1.5.0 +" /> 版本才支持哦~
:::
```
无法渲染成下面的 样式
![image](https://user-images.githubusercontent.com/37894474/147847680-fb7c73d6-2a4c-4e80-877d-6a5e9741d63d.png)

**Comment by Dragon1573** [comment]
目前我的项目中只用到了 `tip` `warning` `center` 和 `details` 这几个容器，在我部署的站点中是能够正常显示的。

此问题建议直接向 @xugaoyi 进行反馈。

**Comment by carveybunt** [comment]
好的 多谢
